# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Tools.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWidget(object):
    def setupUi(self, MainWidget):
        MainWidget.setObjectName("MainWidget")
        MainWidget.resize(1280, 946)
        font = QtGui.QFont()
        font.setFamily("华文细黑")
        font.setPointSize(10)
        MainWidget.setFont(font)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(MainWidget)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.widget_under = QtWidgets.QWidget(MainWidget)
        self.widget_under.setMaximumSize(QtCore.QSize(16777215, 300))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.widget_under.setFont(font)
        self.widget_under.setObjectName("widget_under")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_under)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.widget_2 = QtWidgets.QWidget(self.widget_under)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.widget_2.setFont(font)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_search = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.label_search.setFont(font)
        self.label_search.setObjectName("label_search")
        self.verticalLayout_11.addWidget(self.label_search)
        self.comboBox_kinds = QtWidgets.QComboBox(self.widget_2)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.comboBox_kinds.setFont(font)
        self.comboBox_kinds.setObjectName("comboBox_kinds")
        self.comboBox_kinds.addItem("")
        self.comboBox_kinds.addItem("")
        self.comboBox_kinds.addItem("")
        self.comboBox_kinds.addItem("")
        self.verticalLayout_11.addWidget(self.comboBox_kinds)
        self.textEdit_search = QtWidgets.QTextEdit(self.widget_2)
        self.textEdit_search.setMinimumSize(QtCore.QSize(0, 160))
        self.textEdit_search.setMaximumSize(QtCore.QSize(16777215, 200))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.textEdit_search.setFont(font)
        self.textEdit_search.setObjectName("textEdit_search")
        self.verticalLayout_11.addWidget(self.textEdit_search)
        self.pushButton_search = QtWidgets.QPushButton(self.widget_2)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.pushButton_search.setFont(font)
        self.pushButton_search.setObjectName("pushButton_search")
        self.verticalLayout_11.addWidget(self.pushButton_search)
        self.horizontalLayout_2.addWidget(self.widget_2)
        self.widget_edit = QtWidgets.QWidget(self.widget_under)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.widget_edit.setFont(font)
        self.widget_edit.setObjectName("widget_edit")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.widget_edit)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_edit = QtWidgets.QLabel(self.widget_edit)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.label_edit.setFont(font)
        self.label_edit.setObjectName("label_edit")
        self.verticalLayout_8.addWidget(self.label_edit)
        self.comboBox_edit = QtWidgets.QComboBox(self.widget_edit)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.comboBox_edit.setFont(font)
        self.comboBox_edit.setObjectName("comboBox_edit")
        self.verticalLayout_8.addWidget(self.comboBox_edit)
        self.textEdit_edit = QtWidgets.QTextEdit(self.widget_edit)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.textEdit_edit.setFont(font)
        self.textEdit_edit.setObjectName("textEdit_edit")
        self.verticalLayout_8.addWidget(self.textEdit_edit)
        self.pushButton_add = QtWidgets.QPushButton(self.widget_edit)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.pushButton_add.setFont(font)
        self.pushButton_add.setObjectName("pushButton_add")
        self.verticalLayout_8.addWidget(self.pushButton_add)
        self.pushButton_del = QtWidgets.QPushButton(self.widget_edit)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.pushButton_del.setFont(font)
        self.pushButton_del.setObjectName("pushButton_del")
        self.verticalLayout_8.addWidget(self.pushButton_del)
        self.pushButton_saveconfig = QtWidgets.QPushButton(self.widget_edit)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.pushButton_saveconfig.setFont(font)
        self.pushButton_saveconfig.setObjectName("pushButton_saveconfig")
        self.verticalLayout_8.addWidget(self.pushButton_saveconfig)
        self.pushButton_config = QtWidgets.QPushButton(self.widget_edit)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.pushButton_config.setFont(font)
        self.pushButton_config.setObjectName("pushButton_config")
        self.verticalLayout_8.addWidget(self.pushButton_config)
        self.horizontalLayout_2.addWidget(self.widget_edit)
        self.widget_send = QtWidgets.QWidget(self.widget_under)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.widget_send.setFont(font)
        self.widget_send.setObjectName("widget_send")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_send)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_recipients = QtWidgets.QLabel(self.widget_send)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.label_recipients.setFont(font)
        self.label_recipients.setObjectName("label_recipients")
        self.verticalLayout_2.addWidget(self.label_recipients)
        self.textEdit_recipients = QtWidgets.QTextEdit(self.widget_send)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.textEdit_recipients.setFont(font)
        self.textEdit_recipients.setObjectName("textEdit_recipients")
        self.verticalLayout_2.addWidget(self.textEdit_recipients)
        self.pushButton_mailfile = QtWidgets.QPushButton(self.widget_send)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.pushButton_mailfile.setFont(font)
        self.pushButton_mailfile.setObjectName("pushButton_mailfile")
        self.verticalLayout_2.addWidget(self.pushButton_mailfile)
        self.textEdit_mailfile = QtWidgets.QTextEdit(self.widget_send)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.textEdit_mailfile.setFont(font)
        self.textEdit_mailfile.setObjectName("textEdit_mailfile")
        self.verticalLayout_2.addWidget(self.textEdit_mailfile)
        self.pushButton_send = QtWidgets.QPushButton(self.widget_send)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.pushButton_send.setFont(font)
        self.pushButton_send.setObjectName("pushButton_send")
        self.verticalLayout_2.addWidget(self.pushButton_send)
        self.pushButton_exit = QtWidgets.QPushButton(self.widget_send)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.pushButton_exit.setFont(font)
        self.pushButton_exit.setObjectName("pushButton_exit")
        self.verticalLayout_2.addWidget(self.pushButton_exit)
        self.horizontalLayout_2.addWidget(self.widget_send)
        self.verticalLayout_9.addWidget(self.widget_under)
        self.widget_up = QtWidgets.QWidget(MainWidget)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.widget_up.setFont(font)
        self.widget_up.setObjectName("widget_up")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_up)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.widget_function = QtWidgets.QWidget(self.widget_up)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.widget_function.setFont(font)
        self.widget_function.setObjectName("widget_function")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_function)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_api = QtWidgets.QLabel(self.widget_function)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.label_api.setFont(font)
        self.label_api.setObjectName("label_api")
        self.verticalLayout_4.addWidget(self.label_api)
        self.comboBox_api = QtWidgets.QComboBox(self.widget_function)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.comboBox_api.setFont(font)
        self.comboBox_api.setObjectName("comboBox_api")
        self.verticalLayout_4.addWidget(self.comboBox_api)
        self.textEdit_api = QtWidgets.QTextEdit(self.widget_function)
        self.textEdit_api.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.textEdit_api.setFont(font)
        self.textEdit_api.setObjectName("textEdit_api")
        self.verticalLayout_4.addWidget(self.textEdit_api)
        self.pushButton_ensure = QtWidgets.QPushButton(self.widget_function)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.pushButton_ensure.setFont(font)
        self.pushButton_ensure.setObjectName("pushButton_ensure")
        self.verticalLayout_4.addWidget(self.pushButton_ensure)
        self.label_method = QtWidgets.QLabel(self.widget_function)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.label_method.setFont(font)
        self.label_method.setObjectName("label_method")
        self.verticalLayout_4.addWidget(self.label_method)
        self.comboBox_method = QtWidgets.QComboBox(self.widget_function)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.comboBox_method.setFont(font)
        self.comboBox_method.setObjectName("comboBox_method")
        self.verticalLayout_4.addWidget(self.comboBox_method)
        self.label_user = QtWidgets.QLabel(self.widget_function)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.label_user.setFont(font)
        self.label_user.setObjectName("label_user")
        self.verticalLayout_4.addWidget(self.label_user)
        self.comboBox_user = QtWidgets.QComboBox(self.widget_function)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.comboBox_user.setFont(font)
        self.comboBox_user.setObjectName("comboBox_user")
        self.verticalLayout_4.addWidget(self.comboBox_user)
        self.label_params = QtWidgets.QLabel(self.widget_function)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.label_params.setFont(font)
        self.label_params.setObjectName("label_params")
        self.verticalLayout_4.addWidget(self.label_params)
        self.textEdit_params = QtWidgets.QTextEdit(self.widget_function)
        self.textEdit_params.setMinimumSize(QtCore.QSize(200, 0))
        self.textEdit_params.setMaximumSize(QtCore.QSize(16777215, 120))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.textEdit_params.setFont(font)
        self.textEdit_params.setObjectName("textEdit_params")
        self.verticalLayout_4.addWidget(self.textEdit_params)
        self.label_object = QtWidgets.QLabel(self.widget_function)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.label_object.setFont(font)
        self.label_object.setObjectName("label_object")
        self.verticalLayout_4.addWidget(self.label_object)
        self.textEdit_object = QtWidgets.QTextEdit(self.widget_function)
        self.textEdit_object.setMaximumSize(QtCore.QSize(16777215, 120))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.textEdit_object.setFont(font)
        self.textEdit_object.setObjectName("textEdit_object")
        self.verticalLayout_4.addWidget(self.textEdit_object)
        self.label_condition = QtWidgets.QLabel(self.widget_function)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.label_condition.setFont(font)
        self.label_condition.setObjectName("label_condition")
        self.verticalLayout_4.addWidget(self.label_condition)
        self.textEdit_condition = QtWidgets.QTextEdit(self.widget_function)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.textEdit_condition.setFont(font)
        self.textEdit_condition.setObjectName("textEdit_condition")
        self.verticalLayout_4.addWidget(self.textEdit_condition)
        self.label_back = QtWidgets.QLabel(self.widget_function)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.label_back.setFont(font)
        self.label_back.setObjectName("label_back")
        self.verticalLayout_4.addWidget(self.label_back)
        self.textEdit_back = QtWidgets.QTextEdit(self.widget_function)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.textEdit_back.setFont(font)
        self.textEdit_back.setObjectName("textEdit_back")
        self.verticalLayout_4.addWidget(self.textEdit_back)
        self.horizontalLayout_3.addWidget(self.widget_function)
        self.widget = QtWidgets.QWidget(self.widget_up)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.widget.setFont(font)
        self.widget.setObjectName("widget")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_data = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.label_data.setFont(font)
        self.label_data.setObjectName("label_data")
        self.verticalLayout_10.addWidget(self.label_data)
        self.textEdit_data = QtWidgets.QTextEdit(self.widget)
        self.textEdit_data.setMinimumSize(QtCore.QSize(300, 0))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.textEdit_data.setFont(font)
        self.textEdit_data.setObjectName("textEdit_data")
        self.verticalLayout_10.addWidget(self.textEdit_data)
        self.pushButton_data = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.pushButton_data.setFont(font)
        self.pushButton_data.setObjectName("pushButton_data")
        self.verticalLayout_10.addWidget(self.pushButton_data)
        self.pushButton_file = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.pushButton_file.setFont(font)
        self.pushButton_file.setObjectName("pushButton_file")
        self.verticalLayout_10.addWidget(self.pushButton_file)
        self.horizontalLayout_3.addWidget(self.widget)
        self.widget_info = QtWidgets.QWidget(self.widget_up)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.widget_info.setFont(font)
        self.widget_info.setObjectName("widget_info")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget_info)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_info = QtWidgets.QLabel(self.widget_info)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.label_info.setFont(font)
        self.label_info.setObjectName("label_info")
        self.verticalLayout.addWidget(self.label_info)
        self.textEdit_info = QtWidgets.QTextEdit(self.widget_info)
        self.textEdit_info.setMinimumSize(QtCore.QSize(300, 0))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.textEdit_info.setFont(font)
        self.textEdit_info.setObjectName("textEdit_info")
        self.verticalLayout.addWidget(self.textEdit_info)
        self.pushButton_update = QtWidgets.QPushButton(self.widget_info)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.pushButton_update.setFont(font)
        self.pushButton_update.setObjectName("pushButton_update")
        self.verticalLayout.addWidget(self.pushButton_update)
        self.horizontalLayout_3.addWidget(self.widget_info)
        self.verticalLayout_9.addWidget(self.widget_up)

        self.retranslateUi(MainWidget)
        QtCore.QMetaObject.connectSlotsByName(MainWidget)

    def retranslateUi(self, MainWidget):
        _translate = QtCore.QCoreApplication.translate
        MainWidget.setWindowTitle(_translate("MainWidget", "TB TOOL"))
        self.label_search.setText(_translate("MainWidget", "查询参数（已经写好的方法）"))
        self.comboBox_kinds.setItemText(0, _translate("MainWidget", "企业中所有项目名称及ID"))
        self.comboBox_kinds.setItemText(1, _translate("MainWidget", "项目中所有任务名称及ID（需写入项目ID）"))
        self.comboBox_kinds.setItemText(2, _translate("MainWidget", "项目中所有任务类型名称及ID（需写入项目ID）"))
        self.comboBox_kinds.setItemText(3, _translate("MainWidget", "项目中所有任务分组及ID（需写入项目ID）"))
        self.pushButton_search.setText(_translate("MainWidget", "查询"))
        self.label_edit.setText(_translate("MainWidget", "编辑参数【格式：（参数:值）】"))
        self.pushButton_add.setText(_translate("MainWidget", "更新"))
        self.pushButton_del.setText(_translate("MainWidget", "删除"))
        self.pushButton_saveconfig.setText(_translate("MainWidget", "保存配置"))
        self.pushButton_config.setText(_translate("MainWidget", "载入配置"))
        self.label_recipients.setText(_translate("MainWidget", "收件人【换行输入，尽量不要有空行】"))
        self.textEdit_recipients.setHtml(_translate("MainWidget", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'黑体\',\'黑体\',\'黑体\',\'华文细黑\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'仿宋\';\">qiang.zhang@uwa4d.com</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'仿宋\';\">yixian.wang@uwa4d.com</span></p></body></html>"))
        self.pushButton_mailfile.setText(_translate("MainWidget", "添加文件"))
        self.pushButton_send.setText(_translate("MainWidget", "发送邮件"))
        self.pushButton_exit.setText(_translate("MainWidget", "退出"))
        self.label_api.setText(_translate("MainWidget", "API【url带{}意味着需要自定义路径参数】"))
        self.pushButton_ensure.setText(_translate("MainWidget", "查看"))
        self.label_method.setText(_translate("MainWidget", "Method"))
        self.label_user.setText(_translate("MainWidget", "User"))
        self.label_params.setText(_translate("MainWidget", "Params【格式：（参数:值）】"))
        self.label_object.setText(_translate("MainWidget", "Object【格式：（参数:值）】"))
        self.textEdit_object.setHtml(_translate("MainWidget", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'黑体\',\'黑体\',\'黑体\',\'华文细黑\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'仿宋\';\"><br /></p></body></html>"))
        self.label_condition.setText(_translate("MainWidget", "条件【格式，换行输入（值:IN/NOTIN:条目名）】"))
        self.label_back.setText(_translate("MainWidget", "返回项【（从要求与提示中复制响应中需要的项目名，换行输入）】"))
        self.label_data.setText(_translate("MainWidget", "数据"))
        self.pushButton_data.setText(_translate("MainWidget", "生成数据"))
        self.pushButton_file.setText(_translate("MainWidget", "生成数据文件"))
        self.label_info.setText(_translate("MainWidget", "要求与提示"))
        self.textEdit_info.setHtml(_translate("MainWidget", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'黑体\',\'黑体\',\'黑体\',\'华文细黑\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<h1 style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:120%;\"><span style=\" font-family:\'Open Sans\',\'Clear Sans\',\'Helvetica Neue\',\'Helvetica\',\'Arial\',\'sans-serif\'; font-size:xx-large; font-weight:600; color:#333333;\">UWA公司内部TB工具指南V0.0.1</span></h1>\n"
"<p style=\" margin-top:13px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Open Sans\',\'Clear Sans\',\'Helvetica Neue\',\'Helvetica\',\'Arial\',\'sans-serif\'; font-size:16px; color:#777777;\">本应用旨在一定程度上简化Teambition的检索流程，方便生成报告与发送邮件。由于还没有收到进一步的需求，所以应用的功能还略显单薄，并且无法满足复杂的数据处理要求。下一版本改进的方向有：条件运算符及其功能的添加；新增查询参数；在API中添加更多数据；添加更多的“要求与提示”文档。</span></p>\n"
"<h2 style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:122.5%;\"><span style=\" font-family:\'Open Sans\',\'Clear Sans\',\'Helvetica Neue\',\'Helvetica\',\'Arial\',\'sans-serif\'; font-size:x-large; font-weight:600; color:#333333;\">使用方法</span></h2>\n"
"<h3 style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:143%;\"><span style=\" font-family:\'Open Sans\',\'Clear Sans\',\'Helvetica Neue\',\'Helvetica\',\'Arial\',\'sans-serif\'; font-size:large; font-weight:600; color:#333333;\">查询参数</span></h3>\n"
"<p style=\" margin-top:13px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Open Sans\',\'Clear Sans\',\'Helvetica Neue\',\'Helvetica\',\'Arial\',\'sans-serif\'; font-size:16px; color:#777777;\">在此模块，集成了部分常用方法，对于不需要写入参数的，可以直接点击查询按钮获取结果。对于需要写入的，一般可以通过前期不需要获取参数的方法获取，并将目标项的参数写入文本框中。</span></p>\n"
"<p style=\" margin-top:13px; margin-bottom:13px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Open Sans\',\'Clear Sans\',\'Helvetica Neue\',\'Helvetica\',\'Arial\',\'sans-serif\'; font-size:16px; color:#333333;\">具体方法如下：</span></p>\n"
"<ul style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 1;\"><li style=\" font-family:\'Open Sans\',\'Clear Sans\',\'Helvetica Neue\',\'Helvetica\',\'Arial\',\'sans-serif\'; font-size:16px; color:#333333;\" style=\" margin-top:13px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16px;\">企业中所有项目名称及ID</span></li>\n"
"<ul style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 2;\"><li style=\" font-family:\'Open Sans\',\'Clear Sans\',\'Helvetica Neue\',\'Helvetica\',\'Arial\',\'sans-serif\'; font-size:16px; color:#333333;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16px;\">项目名称，项目ID</span></li></ul>\n"
"<li style=\" font-family:\'Open Sans\',\'Clear Sans\',\'Helvetica Neue\',\'Helvetica\',\'Arial\',\'sans-serif\'; font-size:16px; color:#333333;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16px;\">项目中所有任务名称及ID（需写入项目ID）</span></li>\n"
"<ul style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 2;\"><li style=\" font-family:\'Open Sans\',\'Clear Sans\',\'Helvetica Neue\',\'Helvetica\',\'Arial\',\'sans-serif\'; font-size:16px; color:#333333;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16px;\">任务名称，任务ID</span></li></ul>\n"
"<li style=\" font-family:\'Open Sans\',\'Clear Sans\',\'Helvetica Neue\',\'Helvetica\',\'Arial\',\'sans-serif\'; font-size:16px; color:#333333;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16px;\">项目中所有任务类型名称及ID（需写入项目ID）</span></li>\n"
"<ul style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 2;\"><li style=\" font-family:\'Open Sans\',\'Clear Sans\',\'Helvetica Neue\',\'Helvetica\',\'Arial\',\'sans-serif\'; font-size:16px; color:#333333;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16px;\">任务类型名称，任务类型ID</span></li></ul>\n"
"<li style=\" font-family:\'Open Sans\',\'Clear Sans\',\'Helvetica Neue\',\'Helvetica\',\'Arial\',\'sans-serif\'; font-size:16px; color:#333333;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16px;\">项目中所有任务分组及ID（需写入项目ID）</span></li></ul>\n"
"<ul style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 2;\"><li style=\" font-family:\'Open Sans\',\'Clear Sans\',\'Helvetica Neue\',\'Helvetica\',\'Arial\',\'sans-serif\'; font-size:16px; color:#333333;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16px;\">任务分组名称，任务分组ID</span></li></ul>\n"
"<h3 style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:143%;\"><span style=\" font-family:\'Open Sans\',\'Clear Sans\',\'Helvetica Neue\',\'Helvetica\',\'Arial\',\'sans-serif\'; font-size:large; font-weight:600; color:#333333;\">参数编辑</span></h3>\n"
"<p style=\" margin-top:13px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Open Sans\',\'Clear Sans\',\'Helvetica Neue\',\'Helvetica\',\'Arial\',\'sans-serif\'; font-size:16px; color:#777777;\">在此模块，集成了获取数据所需的所有参数，包括Url，Method，User，Params，Object，条件，返回项。其格式根据提示书写即可，范例将在下方给出。</span></p>\n"
"<p style=\" margin-top:13px; margin-bottom:13px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Open Sans\',\'Clear Sans\',\'Helvetica Neue\',\'Helvetica\',\'Arial\',\'sans-serif\'; font-size:16px; color:#333333;\">具体条目如下：</span></p>\n"
"<ul style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 1;\"><li style=\" font-family:\'Open Sans\',\'Clear Sans\',\'Helvetica Neue\',\'Helvetica\',\'Arial\',\'sans-serif\'; font-size:16px; color:#333333;\" style=\" margin-top:13px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16px;\">API</span></li>\n"
"<ul style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 2;\"><li style=\" font-family:\'Open Sans\',\'Clear Sans\',\'Helvetica Neue\',\'Helvetica\',\'Arial\',\'sans-serif\'; font-size:16px; color:#333333;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16px;\">选择后必须点击</span><span style=\" font-family:\'Courier New\'; font-size:16px; background-color:#f3f4f4;\">查看</span><span style=\" font-size:16px;\">按钮，检查url是否需要改写</span></li>\n"
"<li style=\" font-family:\'Open Sans\',\'Clear Sans\',\'Helvetica Neue\',\'Helvetica\',\'Arial\',\'sans-serif\'; font-size:16px; color:#333333;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16px;\">例如：</span><span style=\" font-family:\'Courier New\'; font-size:16px; background-color:#f3f4f4;\">https://open.teambition.com/api/v3/project/{projectId}/scenariofieldconfig/search</span></li>\n"
"<li style=\" font-family:\'Open Sans\',\'Clear Sans\',\'Helvetica Neue\',\'Helvetica\',\'Arial\',\'sans-serif\'; font-size:16px; color:#333333;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16px;\">其中</span><span style=\" font-family:\'Courier New\'; font-size:16px; background-color:#f3f4f4;\">{projectId}</span><span style=\" font-size:16px;\">需要替换为相应的项目ID</span></li></ul>\n"
"<li style=\" font-family:\'Open Sans\',\'Clear Sans\',\'Helvetica Neue\',\'Helvetica\',\'Arial\',\'sans-serif\'; font-size:16px; color:#333333;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16px;\">Method</span></li>\n"
"<ul style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 2;\"><li style=\" font-family:\'Open Sans\',\'Clear Sans\',\'Helvetica Neue\',\'Helvetica\',\'Arial\',\'sans-serif\'; font-size:16px; color:#333333;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16px;\">根据文档中列出信息选择</span></li></ul>\n"
"<li style=\" font-family:\'Open Sans\',\'Clear Sans\',\'Helvetica Neue\',\'Helvetica\',\'Arial\',\'sans-serif\'; font-size:16px; color:#333333;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16px;\">User</span></li>\n"
"<ul style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 2;\"><li style=\" font-family:\'Open Sans\',\'Clear Sans\',\'Helvetica Neue\',\'Helvetica\',\'Arial\',\'sans-serif\'; font-size:16px; color:#333333;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16px;\">在当前功能中并不重要</span></li></ul>\n"
"<li style=\" font-family:\'Open Sans\',\'Clear Sans\',\'Helvetica Neue\',\'Helvetica\',\'Arial\',\'sans-serif\'; font-size:16px; color:#333333;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16px;\">Params</span></li>\n"
"<ul style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 2;\"><li style=\" font-family:\'Open Sans\',\'Clear Sans\',\'Helvetica Neue\',\'Helvetica\',\'Arial\',\'sans-serif\'; font-size:16px; color:#333333;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16px;\">查询参数，需要查看文档中是否有必填选项</span></li>\n"
"<li style=\" font-family:\'Open Sans\',\'Clear Sans\',\'Helvetica Neue\',\'Helvetica\',\'Arial\',\'sans-serif\'; font-size:16px; color:#333333;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16px;\">例如：</span></li>\n"
"<p style=\" margin-top:15px; margin-bottom:15px; margin-left:0px; margin-right:0px; -qt-block-indent:2; text-indent:0px; background-color:#f8f8f8;\"><span style=\" font-family:\'Courier New\'; font-size:16px; color:#333333;\">tql:_projectId={projectId} AND isArchived = false<br />pageSize:4000</span></p>\n"
"<li style=\" font-family:\'Open Sans\',\'Clear Sans\',\'Helvetica Neue\',\'Helvetica\',\'Arial\',\'sans-serif\'; font-size:16px; color:#333333;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16px;\">因为现在还不支持整数输入，所以pageSize已经整体置为4000</span></li></ul>\n"
"<li style=\" font-family:\'Open Sans\',\'Clear Sans\',\'Helvetica Neue\',\'Helvetica\',\'Arial\',\'sans-serif\'; font-size:16px; color:#333333;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16px;\">Object</span></li>\n"
"<ul style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 2;\"><li style=\" font-family:\'Open Sans\',\'Clear Sans\',\'Helvetica Neue\',\'Helvetica\',\'Arial\',\'sans-serif\'; font-size:16px; color:#333333;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16px;\">请求体，格式同上</span></li></ul>\n"
"<li style=\" font-family:\'Open Sans\',\'Clear Sans\',\'Helvetica Neue\',\'Helvetica\',\'Arial\',\'sans-serif\'; font-size:16px; color:#333333;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16px;\">条件</span></li>\n"
"<ul style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 2;\"><li style=\" font-family:\'Open Sans\',\'Clear Sans\',\'Helvetica Neue\',\'Helvetica\',\'Arial\',\'sans-serif\'; font-size:16px; color:#333333;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16px;\">当前版本只集成了</span><span style=\" font-family:\'Courier New\'; font-size:16px; background-color:#f3f4f4;\">IN/NOTIN</span><span style=\" font-size:16px;\">的方法，用于筛选数据中，有或没有指定值的条目的数据项</span></li>\n"
"<li style=\" font-family:\'Open Sans\',\'Clear Sans\',\'Helvetica Neue\',\'Helvetica\',\'Arial\',\'sans-serif\'; font-size:16px; color:#333333;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16px;\">例如:</span></li>\n"
"<p style=\" margin-top:15px; margin-bottom:15px; margin-left:0px; margin-right:0px; -qt-block-indent:2; text-indent:0px; background-color:#f8f8f8;\"><span style=\" font-family:\'Courier New\'; font-size:16px; color:#333333;\">23862dhiaugd IN tasklistId # 筛选在某一任务列表下的数据项<br />97840923skasdn NOTIN customfields # 筛选自定义字段列表下没有指定值的数据项</span></p>\n"
"<li style=\" font-family:\'Open Sans\',\'Clear Sans\',\'Helvetica Neue\',\'Helvetica\',\'Arial\',\'sans-serif\'; font-size:16px; color:#333333;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16px;\">可以多条件层层筛选</span></li></ul>\n"
"<li style=\" font-family:\'Open Sans\',\'Clear Sans\',\'Helvetica Neue\',\'Helvetica\',\'Arial\',\'sans-serif\'; font-size:16px; color:#333333;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16px;\">返回项</span></li></ul>\n"
"<ul style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 2;\"><li style=\" font-family:\'Open Sans\',\'Clear Sans\',\'Helvetica Neue\',\'Helvetica\',\'Arial\',\'sans-serif\'; font-size:16px; color:#333333;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16px;\">指定返回的结果有哪些条目</span></li>\n"
"<li style=\" font-family:\'Open Sans\',\'Clear Sans\',\'Helvetica Neue\',\'Helvetica\',\'Arial\',\'sans-serif\'; font-size:16px; color:#333333;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16px;\">例如：</span></li>\n"
"<p style=\" margin-top:15px; margin-bottom:15px; margin-left:0px; margin-right:0px; -qt-block-indent:2; text-indent:0px; background-color:#f8f8f8;\"><span style=\" font-family:\'Courier New\'; font-size:16px; color:#333333;\">content<br />startDate<br />note</span></p>\n"
"<li style=\" font-family:\'Open Sans\',\'Clear Sans\',\'Helvetica Neue\',\'Helvetica\',\'Arial\',\'sans-serif\'; font-size:16px; color:#333333;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16px;\">则在</span><span style=\" font-family:\'Courier New\'; font-size:16px; background-color:#f3f4f4;\">数据</span><span style=\" font-size:16px;\">文本框中每一条数据会返回</span><span style=\" font-family:\'Courier New\'; font-size:16px; background-color:#f3f4f4;\">任务内容、开始时间、备注</span><span style=\" font-size:16px;\">三种信息</span></li></ul>\n"
"<h3 style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:143%;\"><span style=\" font-family:\'Open Sans\',\'Clear Sans\',\'Helvetica Neue\',\'Helvetica\',\'Arial\',\'sans-serif\'; font-size:large; font-weight:600; color:#333333;\">编辑参数</span></h3>\n"
"<ul style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 1;\"><li style=\" font-family:\'Open Sans\',\'Clear Sans\',\'Helvetica Neue\',\'Helvetica\',\'Arial\',\'sans-serif\'; font-size:16px; color:#333333;\" style=\" margin-top:13px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16px;\">更新</span></li>\n"
"<ul style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 2;\"><li style=\" font-family:\'Open Sans\',\'Clear Sans\',\'Helvetica Neue\',\'Helvetica\',\'Arial\',\'sans-serif\'; font-size:16px; color:#333333;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16px;\">将条目与值存入</span><span style=\" font-family:\'Courier New\'; font-size:16px; background-color:#f3f4f4;\">data/config.json</span><span style=\" font-size:16px;\">并更新GUI中内容</span></li>\n"
"<li style=\" font-family:\'Open Sans\',\'Clear Sans\',\'Helvetica Neue\',\'Helvetica\',\'Arial\',\'sans-serif\'; font-size:16px; color:#333333;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16px;\">例如:选择API；</span><span style=\" font-family:\'Courier New\'; font-size:16px; background-color:#f3f4f4;\">获取公司所有项目:https://open.teambition.com/api/project/query</span></li></ul>\n"
"<li style=\" font-family:\'Open Sans\',\'Clear Sans\',\'Helvetica Neue\',\'Helvetica\',\'Arial\',\'sans-serif\'; font-size:16px; color:#333333;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16px;\">删除</span></li>\n"
"<ul style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 2;\"><li style=\" font-family:\'Open Sans\',\'Clear Sans\',\'Helvetica Neue\',\'Helvetica\',\'Arial\',\'sans-serif\'; font-size:16px; color:#333333;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16px;\">删除文件及GUI中相应条目</span></li>\n"
"<li style=\" font-family:\'Open Sans\',\'Clear Sans\',\'Helvetica Neue\',\'Helvetica\',\'Arial\',\'sans-serif\'; font-size:16px; color:#333333;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16px;\">例如:</span><span style=\" font-family:\'Courier New\'; font-size:16px; background-color:#f3f4f4;\">获取公司所有项目</span></li></ul>\n"
"<li style=\" font-family:\'Open Sans\',\'Clear Sans\',\'Helvetica Neue\',\'Helvetica\',\'Arial\',\'sans-serif\'; font-size:16px; color:#333333;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16px;\">保存配置</span></li>\n"
"<ul style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 2;\"><li style=\" font-family:\'Open Sans\',\'Clear Sans\',\'Helvetica Neue\',\'Helvetica\',\'Arial\',\'sans-serif\'; font-size:16px; color:#333333;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16px;\">在data文件夹下保存自命名数据文件，以便下次再用，并且可以写自动化脚本运行</span></li></ul>\n"
"<li style=\" font-family:\'Open Sans\',\'Clear Sans\',\'Helvetica Neue\',\'Helvetica\',\'Arial\',\'sans-serif\'; font-size:16px; color:#333333;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16px;\">载入配置</span></li></ul>\n"
"<ul style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 2;\"><li style=\" font-family:\'Open Sans\',\'Clear Sans\',\'Helvetica Neue\',\'Helvetica\',\'Arial\',\'sans-serif\'; font-size:16px; color:#333333;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16px;\">选择配置文件完成快速搭建</span></li></ul>\n"
"<h3 style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:143%;\"><span style=\" font-family:\'Open Sans\',\'Clear Sans\',\'Helvetica Neue\',\'Helvetica\',\'Arial\',\'sans-serif\'; font-size:large; font-weight:600; color:#333333;\">数据</span></h3>\n"
"<ul style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 1;\"><li style=\" font-family:\'Open Sans\',\'Clear Sans\',\'Helvetica Neue\',\'Helvetica\',\'Arial\',\'sans-serif\'; font-size:16px; color:#333333;\" style=\" margin-top:13px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16px;\">文本框</span></li>\n"
"<ul style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 2;\"><li style=\" font-family:\'Open Sans\',\'Clear Sans\',\'Helvetica Neue\',\'Helvetica\',\'Arial\',\'sans-serif\'; font-size:16px; color:#333333;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16px;\">可以在生成数据后手工编辑相关文字，作为邮件正文发送</span></li></ul>\n"
"<li style=\" font-family:\'Open Sans\',\'Clear Sans\',\'Helvetica Neue\',\'Helvetica\',\'Arial\',\'sans-serif\'; font-size:16px; color:#333333;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16px;\">生成数据</span></li>\n"
"<ul style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 2;\"><li style=\" font-family:\'Open Sans\',\'Clear Sans\',\'Helvetica Neue\',\'Helvetica\',\'Arial\',\'sans-serif\'; font-size:16px; color:#333333;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16px;\">字面意思</span></li></ul>\n"
"<li style=\" font-family:\'Open Sans\',\'Clear Sans\',\'Helvetica Neue\',\'Helvetica\',\'Arial\',\'sans-serif\'; font-size:16px; color:#333333;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16px;\">生成数据文件</span></li></ul>\n"
"<ul style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 2;\"><li style=\" font-family:\'Open Sans\',\'Clear Sans\',\'Helvetica Neue\',\'Helvetica\',\'Arial\',\'sans-serif\'; font-size:16px; color:#333333;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16px;\">字面意思，默认保存在Temporaryfile文件夹中</span></li></ul>\n"
"<h3 style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:143%;\"><span style=\" font-family:\'Open Sans\',\'Clear Sans\',\'Helvetica Neue\',\'Helvetica\',\'Arial\',\'sans-serif\'; font-size:large; font-weight:600; color:#333333;\">发送邮件</span></h3>\n"
"<ul style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 1;\"><li style=\" font-family:\'Open Sans\',\'Clear Sans\',\'Helvetica Neue\',\'Helvetica\',\'Arial\',\'sans-serif\'; font-size:16px; color:#333333;\" style=\" margin-top:13px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16px;\">收件人</span></li>\n"
"<ul style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 2;\"><li style=\" font-family:\'Open Sans\',\'Clear Sans\',\'Helvetica Neue\',\'Helvetica\',\'Arial\',\'sans-serif\'; font-size:16px; color:#333333;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16px;\">换行输入邮箱地址</span></li></ul>\n"
"<li style=\" font-family:\'Open Sans\',\'Clear Sans\',\'Helvetica Neue\',\'Helvetica\',\'Arial\',\'sans-serif\'; font-size:16px; color:#333333;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16px;\">添加文件</span></li>\n"
"<ul style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 2;\"><li style=\" font-family:\'Open Sans\',\'Clear Sans\',\'Helvetica Neue\',\'Helvetica\',\'Arial\',\'sans-serif\'; font-size:16px; color:#333333;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16px;\">字面意思</span></li></ul>\n"
"<li style=\" font-family:\'Open Sans\',\'Clear Sans\',\'Helvetica Neue\',\'Helvetica\',\'Arial\',\'sans-serif\'; font-size:16px; color:#333333;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16px;\">发送邮件</span></li>\n"
"<ul style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 2;\"><li style=\" font-family:\'Open Sans\',\'Clear Sans\',\'Helvetica Neue\',\'Helvetica\',\'Arial\',\'sans-serif\'; font-size:16px; color:#333333;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16px;\">字面意思</span></li></ul>\n"
"<li style=\" font-family:\'Open Sans\',\'Clear Sans\',\'Helvetica Neue\',\'Helvetica\',\'Arial\',\'sans-serif\'; font-size:16px; color:#333333;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16px;\">退出</span></li></ul>\n"
"<ul style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 2;\"><li style=\" font-family:\'Open Sans\',\'Clear Sans\',\'Helvetica Neue\',\'Helvetica\',\'Arial\',\'sans-serif\'; font-size:16px; color:#333333;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16px;\">删除Temporaryfile中文件，退出程序</span></li></ul>\n"
"<h3 style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:143%;\"><span style=\" font-family:\'Open Sans\',\'Clear Sans\',\'Helvetica Neue\',\'Helvetica\',\'Arial\',\'sans-serif\'; font-size:large; font-weight:600; color:#333333;\">要求与提示</span></h3>\n"
"<ul style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 1;\"><li style=\" font-family:\'Open Sans\',\'Clear Sans\',\'Helvetica Neue\',\'Helvetica\',\'Arial\',\'sans-serif\'; font-size:16px; color:#333333;\" style=\" margin-top:13px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16px;\">在选择API后点击刷新按钮，即可获得对应提示</span></li></ul>\n"
"<h2 style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:122.5%;\"><span style=\" font-family:\'Open Sans\',\'Clear Sans\',\'Helvetica Neue\',\'Helvetica\',\'Arial\',\'sans-serif\'; font-size:x-large; font-weight:600; color:#333333;\">使用目的</span></h2>\n"
"<p style=\" margin-top:13px; margin-bottom:13px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Open Sans\',\'Clear Sans\',\'Helvetica Neue\',\'Helvetica\',\'Arial\',\'sans-serif\'; font-size:16px; color:#333333;\">没有想好</span></p>\n"
"<h2 style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:122.5%;\"><span style=\" font-family:\'Open Sans\',\'Clear Sans\',\'Helvetica Neue\',\'Helvetica\',\'Arial\',\'sans-serif\'; font-size:x-large; font-weight:600; color:#333333;\">注意事项</span></h2>\n"
"<ul style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 1;\"><li style=\" font-family:\'Open Sans\',\'Clear Sans\',\'Helvetica Neue\',\'Helvetica\',\'Arial\',\'sans-serif\'; font-size:16px; color:#333333;\" style=\" margin-top:13px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16px;\">没有出现预期结果，先检查各处输入数据是否正确（特别是格式）</span></li>\n"
"<li style=\" font-family:\'Open Sans\',\'Clear Sans\',\'Helvetica Neue\',\'Helvetica\',\'Arial\',\'sans-serif\'; font-size:16px; color:#333333;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16px;\">若检查无误，可以提交源码检查</span><span style=\" font-family:\'仿宋\'; font-size:16px;\"><br /></span></li></ul></body></html>"))
        self.pushButton_update.setText(_translate("MainWidget", "刷新"))
