# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SendMail.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_widget_main(object):
    def setupUi(self, widget_main):
        widget_main.setObjectName("widget_main")
        widget_main.resize(751, 482)
        widget_main.setStyleSheet("QWidget{\n"
"    background-color: rgb(255,195,195);\n"
"    font-family: Lucida Bright;\n"
"    }\n"
"QPushButton{\n"
"    background-color: gray;\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-color: beige;\n"
"    border-radius: 14px;\n"
"    padding: 6px;\n"
"    font-family: Lucida Bright;\n"
"    }\n"
"QWidget#MainWidget{\n"
"    background-color: rgb(240,248,255);\n"
"    font-family: Lucida Bright;\n"
"    }\n"
"QLabel{\n"
"    font-family: Lucida Bright;\n"
"    }\n"
"QTextEdit{\n"
"    font-family: Lucida Bright;\n"
"    }\n"
"QComboBox{\n"
"    font-family: Lucida Bright;\n"
"    }\n"
"")
        self.horizontalLayout = QtWidgets.QHBoxLayout(widget_main)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget_4 = QtWidgets.QWidget(widget_main)
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_content = QtWidgets.QLabel(self.widget_4)
        self.label_content.setObjectName("label_content")
        self.verticalLayout_2.addWidget(self.label_content)
        self.textEdit_content = QtWidgets.QTextEdit(self.widget_4)
        self.textEdit_content.setObjectName("textEdit_content")
        self.verticalLayout_2.addWidget(self.textEdit_content)
        self.pushButton_attach = QtWidgets.QPushButton(self.widget_4)
        self.pushButton_attach.setObjectName("pushButton_attach")
        self.verticalLayout_2.addWidget(self.pushButton_attach)
        self.pushButton_filedata = QtWidgets.QPushButton(self.widget_4)
        self.pushButton_filedata.setObjectName("pushButton_filedata")
        self.verticalLayout_2.addWidget(self.pushButton_filedata)
        self.horizontalLayout.addWidget(self.widget_4)
        self.widget = QtWidgets.QWidget(widget_main)
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_recipient = QtWidgets.QLabel(self.widget)
        self.label_recipient.setObjectName("label_recipient")
        self.verticalLayout.addWidget(self.label_recipient)
        self.textEdit_send = QtWidgets.QTextEdit(self.widget)
        self.textEdit_send.setObjectName("textEdit_send")
        self.verticalLayout.addWidget(self.textEdit_send)
        self.comboBox_recipient = QtWidgets.QComboBox(self.widget)
        self.comboBox_recipient.setObjectName("comboBox_recipient")
        self.verticalLayout.addWidget(self.comboBox_recipient)
        self.pushButton_recipient = QtWidgets.QPushButton(self.widget)
        self.pushButton_recipient.setObjectName("pushButton_recipient")
        self.verticalLayout.addWidget(self.pushButton_recipient)
        self.label_sender = QtWidgets.QLabel(self.widget)
        self.label_sender.setObjectName("label_sender")
        self.verticalLayout.addWidget(self.label_sender)
        self.comboBox_sender = QtWidgets.QComboBox(self.widget)
        self.comboBox_sender.setObjectName("comboBox_sender")
        self.verticalLayout.addWidget(self.comboBox_sender)
        self.pushButton_sender = QtWidgets.QPushButton(self.widget)
        self.pushButton_sender.setObjectName("pushButton_sender")
        self.verticalLayout.addWidget(self.pushButton_sender)
        self.horizontalLayout.addWidget(self.widget)

        self.retranslateUi(widget_main)
        QtCore.QMetaObject.connectSlotsByName(widget_main)

    def retranslateUi(self, widget_main):
        _translate = QtCore.QCoreApplication.translate
        widget_main.setWindowTitle(_translate("widget_main", "Send Mail"))
        self.label_content.setText(_translate("widget_main", "Content"))
        self.pushButton_attach.setText(_translate("widget_main", "Add File As Attachment"))
        self.pushButton_filedata.setText(_translate("widget_main", "Add FileData Into Content"))
        self.label_recipient.setText(_translate("widget_main", "Recipients"))
        self.pushButton_recipient.setText(_translate("widget_main", "Add Recipient"))
        self.label_sender.setText(_translate("widget_main", "Sender"))
        self.pushButton_sender.setText(_translate("widget_main", "Send"))
